#!/bin/bash
# SUPER-HARD HOOK companion — ensure the MANDATORY design skills are installed.
# Runs on SessionStart ("Run the guide and hooks"). Idempotent:
#   * If the skills are already present (they ship vendored with this repo) it
#     just confirms and exits fast — no network.
#   * If any are missing (e.g. a stripped checkout) it (re)installs them:
#       - ui-ux-pro-max  → via its official npm CLI (uipro init --ai claude)
#       - frontend-design → from the anthropics/skills repo
# Never fails the session (always exits 0).
set -uo pipefail

PROJ="${CLAUDE_PROJECT_DIR:-$PWD}"
SKILLS="$PROJ/.claude/skills"
mkdir -p "$SKILLS"

# ui-ux-pro-max ships as a family of skills generated by its CLI.
UIPRO_SKILLS="ui-ux-pro-max ui-styling design design-system brand banner-design slides"

need_uipro=0
for s in $UIPRO_SKILLS; do
  [ -f "$SKILLS/$s/SKILL.md" ] || need_uipro=1
done
need_fd=0
[ -f "$SKILLS/frontend-design/SKILL.md" ] || need_fd=1

if [ "$need_uipro" -eq 0 ] && [ "$need_fd" -eq 0 ]; then
  echo "[skills] mandatory skills present: ui-ux-pro-max (+family) + frontend-design — OK"
  exit 0
fi

# --- ui-ux-pro-max (npm) ---------------------------------------------------
if [ "$need_uipro" -eq 1 ]; then
  if command -v npx >/dev/null 2>&1; then
    echo "[skills] installing ui-ux-pro-max via npm (uipro init --ai claude) ..."
    if ( cd "$PROJ" && printf '\n' | npx --yes -p ui-ux-pro-max-cli uipro init --ai claude ) >/dev/null 2>&1; then
      echo "[skills] ui-ux-pro-max installed"
    else
      echo "(!) ui-ux-pro-max install failed — run manually: npx -p ui-ux-pro-max-cli uipro init --ai claude"
    fi
  else
    echo "(!) npm/npx not found — install Node.js, then: npx -p ui-ux-pro-max-cli uipro init --ai claude"
  fi
fi

# --- frontend-design (git) -------------------------------------------------
if [ "$need_fd" -eq 1 ]; then
  if command -v git >/dev/null 2>&1; then
    echo "[skills] installing frontend-design (anthropics/skills) ..."
    tmp="$(mktemp -d)"
    if git clone --depth 1 --filter=blob:none --sparse https://github.com/anthropics/skills.git "$tmp" >/dev/null 2>&1 \
       && ( cd "$tmp" && git sparse-checkout set skills/frontend-design >/dev/null 2>&1 ) \
       && [ -d "$tmp/skills/frontend-design" ]; then
      mkdir -p "$SKILLS/frontend-design"
      cp -r "$tmp/skills/frontend-design/." "$SKILLS/frontend-design/"
      echo "[skills] frontend-design installed"
    else
      echo "(!) frontend-design fetch failed — see https://github.com/anthropics/skills/tree/main/skills/frontend-design"
    fi
    rm -rf "$tmp"
  else
    echo "(!) git not found — cannot fetch frontend-design"
  fi
fi

exit 0
